version: '3'
services:
  next:
    build: .
    volumes:
      - .:/usr/src/app
    command: bash -c " npm install && npm run dev"
    ports:
      - "3000:3000"
    networks:
      - anime-server_sail
networks:
  anime-server_sail:
    external: true