import Head from 'next/head'

import Navbar from '../components/Navbar'
import { useHandleLogout } from '../hooks/useLogout'

const Home = () => {
  const handleLogout = useHandleLogout()

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </Head>
      <div>
        <Navbar handleLogout={handleLogout} />
      </div>
    </>
  )
}

export default Home
