import Head from 'next/head'
import {apiServer} from "../utills/axios";
import {User, UserResponse} from "../types/User";
import { NextPage } from 'next';

interface Props {
  data: User
}

export async function getServerSideProps() {
  let data: User = {
    id: 0,
    name: '',
    email: '',
    image: '',
    age: 0,
    sex: 0,
    email_verified_at: '',
    updated_at: '',
    created_at: ''
  }
  await apiServer.get<UserResponse>('test')
      .then((res) => {
        data = {
          id: res.data.id,
          name: res.data.name,
          email: res.data.email,
          image: res.data.image,
          age: res.data.age,
          sex: res.data.sex,
          email_verified_at: res.data.email_verified_at,
          updated_at: res.data.updated_at,
          created_at: res.data.created_at
        }
      }).catch(err => {
        console.error(err)
      })
  return {
    props: {
      data
    }
  }
}

const Home: NextPage<Props> = (props) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          { props.data.name }
        </div>
      </main>
    </>
  )
}

export default Home